# 02-1. API 사용하기

## JSON (JavaScript Object Notation)

### 파이썬 객체를 JSON 문자열로 변환 (json.dumps)

In [1]:
d = {"name" : "혼자 공부하는 데이터 분석"}
print(d['name'])

혼자 공부하는 데이터 분석

In [2]:
pip install json

Note: you may need to restart the kernel to use updated packages.

ERROR: Could not find a version that satisfies the requirement json (from versions: none)
ERROR: No matching distribution found for json

In [ ]:
import json

d_str = json.dumps(d, ensure_ascii=False) # ensure_ascii=False 옵션은 한글이 깨지지 않도록 함
# d_str은 JSON 문자열
print(d_str)

{"name": "혼자 공부하는 데이터 분석"}

In [5]:
print(type(d_str))

<class 'str'>

### JSON 문자열을 파이썬 객체로 변환 (json.loads)

In [8]:
d2 = json.loads(d_str) # JSON 문자열을 파이썬 객체로 변환
print(d2['name'])

혼자 공부하는 데이터 분석

In [9]:
print(type(d2))

<class 'dict'>

### json 패키지 이용한 변환 활용

In [10]:
d3 = json.loads('{"name":"혼자 공부하는 데이터 분석", "author":"박해선", "year":2022}')
print(d3['name'])
print(d3['author'])
print(d3['year'])

혼자 공부하는 데이터 분석
박해선
2022

In [11]:
d3 = json.loads('{"name":"혼자 공부하는 데이터 분석", "author":["박해선", "홍길동"], "year":2022}')
print(d3['author'][1])

홍길동

In [12]:
d4_str = """
[
    {"name":"혼자 공부하는 데이터 분석", "author":"박해선", "year":2022},
    {"name":"혼자 공부하는 머신러닝+딥러닝", "author":"박해선", "year":2020}
]
"""
d4 = json.loads(d4_str)
print(d4[0]['name'])

혼자 공부하는 데이터 분석

### JSON 문자열을 DataFrame으로 변환 (read_json)

In [ ]:
from io import StringIO
import pandas as pd
pd.read_json(StringIO(d4_str)) # d4_str 문자열을 DataFrame으로 변환

               name author  year
0    혼자 공부하는 데이터 분석    박해선  2022
1  혼자 공부하는 머신러닝+딥러닝    박해선  2020

In [ ]:
pd.DataFrame(d4) # d4 리스트(파이썬 객체)를 DataFrame으로 변환

               name author  year
0    혼자 공부하는 데이터 분석    박해선  2022
1  혼자 공부하는 머신러닝+딥러닝    박해선  2020

## XML (eXtensible Markup Language)