# 02-1. API 사용하기

## JSON (JavaScript Object Notation)

### 파이썬 객체를 JSON 문자열로 변환 (json.dumps)

In [1]:
d = {"name" : "혼자 공부하는 데이터 분석"}
print(d['name'])

혼자 공부하는 데이터 분석

In [2]:
pip install json

Note: you may need to restart the kernel to use updated packages.

ERROR: Could not find a version that satisfies the requirement json (from versions: none)
ERROR: No matching distribution found for json

In [ ]:
import json

d_str = json.dumps(d, ensure_ascii=False) # ensure_ascii=False 옵션은 한글이 깨지지 않도록 함
# d_str은 JSON 문자열
print(d_str)

{"name": "혼자 공부하는 데이터 분석"}

In [5]:
print(type(d_str))

<class 'str'>

### JSON 문자열을 파이썬 객체로 변환 (json.loads)

In [8]:
d2 = json.loads(d_str) # JSON 문자열을 파이썬 객체로 변환
print(d2['name'])

혼자 공부하는 데이터 분석

In [9]:
print(type(d2))

<class 'dict'>

### json 패키지 이용한 변환 활용

In [10]:
d3 = json.loads('{"name":"혼자 공부하는 데이터 분석", "author":"박해선", "year":2022}')
print(d3['name'])
print(d3['author'])
print(d3['year'])

혼자 공부하는 데이터 분석
박해선
2022

In [11]:
d3 = json.loads('{"name":"혼자 공부하는 데이터 분석", "author":["박해선", "홍길동"], "year":2022}')
print(d3['author'][1])

홍길동

In [12]:
d4_str = """
[
    {"name":"혼자 공부하는 데이터 분석", "author":"박해선", "year":2022},
    {"name":"혼자 공부하는 머신러닝+딥러닝", "author":"박해선", "year":2020}
]
"""
d4 = json.loads(d4_str)
print(d4[0]['name'])

혼자 공부하는 데이터 분석

### JSON 문자열을 DataFrame으로 변환 (read_json)

In [ ]:
from io import StringIO
import pandas as pd
pd.read_json(StringIO(d4_str)) # d4_str 문자열을 DataFrame으로 변환

               name author  year
0    혼자 공부하는 데이터 분석    박해선  2022
1  혼자 공부하는 머신러닝+딥러닝    박해선  2020

In [ ]:
pd.DataFrame(d4) # d4 리스트(파이썬 객체)를 DataFrame으로 변환

               name author  year
0    혼자 공부하는 데이터 분석    박해선  2022
1  혼자 공부하는 머신러닝+딥러닝    박해선  2020

## XML (eXtensible Markup Language)

### XML 문자열을 파이썬 객체로 변환 (fromstring)

In [1]:
x_str = """
<book>
    <name>혼자 공부하는 데이터 분석</name>
    <author>박해선</author>
    <year>2022</year>
</book>
"""

In [2]:
pip install xml.etree.ElementTree

Note: you may need to restart the kernel to use updated packages.

ERROR: Could not find a version that satisfies the requirement xml.etree.ElementTree (from versions: none)
ERROR: No matching distribution found for xml.etree.ElementTree

In [5]:
import xml.etree.ElementTree as et
book = et.fromstring(x_str)
print(type(book))

print(book.tag)

<class 'xml.etree.ElementTree.Element'>
book

### 자식 엘리먼트 확인 (findtext)

In [6]:
book_childs = list(book)
print(book_childs)

[<Element 'name' at 0x000002B13F352E30>, <Element 'author' at 0x000002B13F352E80>, <Element 'year' at 0x000002B13F352F20>]

In [7]:
name, author, year = book_childs
print(name.text)
print(author.text)
print(year.text)

혼자 공부하는 데이터 분석
박해선
2022

In [8]:
name = book.findtext('name')
author = book.findtext('author')
year = book.findtext('year')
print(name)
print(author)
print(year)

혼자 공부하는 데이터 분석
박해선
2022

### 여러 개의 자식 엘리먼트 확인 (findall, for문)

In [9]:
x2_str = """
<books>
    <book>
        <name>혼자 공부하는 데이터 분석</name>
        <author>박해선</author>
        <year>2022</year>
    </book>
    <book>
        <name>혼자 공부하는 머신러닝+딥러닝</name>
        <author>박해선</author>
        <year>2020</year>
    </book>
</books>
"""

In [10]:
books = et.fromstring(x2_str)
print(books.tag)

books

In [11]:
for book in books.findall('book'):
    name = book.findtext('name')
    author = book.findtext('author')
    year = book.findtext('year')
    print(name)
    print(author)
    print(year)
    print()

혼자 공부하는 데이터 분석
박해선
2022

혼자 공부하는 머신러닝+딥러닝
박해선
2020

## 공개 API에서 JSON 데이터 자동으로 추출하기 (도서관 정보나루)

### 파이썬으로 API 호출하기 (requests 패키지)

In [12]:
pip install requests

Requirement already satisfied: requests in c:\Users\LG\Desktop\Zip\Python_Study\python-data-analysis-study\.venv\Lib\site-packages (2.34.2)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\Users\LG\Desktop\Zip\Python_Study\python-data-analysis-study\.venv\Lib\site-packages (from requests) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in c:\Users\LG\Desktop\Zip\Python_Study\python-data-analysis-study\.venv\Lib\site-packages (from requests) (3.18)
Requirement already satisfied: urllib3<3,>=1.26 in c:\Users\LG\Desktop\Zip\Python_Study\python-data-analysis-study\.venv\Lib\site-packages (from requests) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in c:\Users\LG\Desktop\Zip\Python_Study\python-data-analysis-study\.venv\Lib\site-packages (from requests) (2026.6.17)
Note: you may need to restart the kernel to use updated packages.

In [14]:
import requests

In [15]:
url = "http://data4library.kr/api/loanItemSrch?format=json&startDt=2021-04-01&endDt=2021-04-30&age=20&authKey=821769091be90603df45a8b965c4f17bfc29ba614663420d5e25777d5936b08d"

In [16]:
r = requests.get(url)

In [17]:
data = r.json()
print(data)

{'response': {'errCode': 'vitalizationErr', 'error': 'API 활성화 상태가아닙니다.'}}

In [18]:
books = []
for d in data['response']['docs']:
    books.append(d['doc'])

KeyError: 'docs'

In [19]:
books

[]

In [20]:
books_df = pd.DataFrame(books)
books_df

NameError: name 'pd' is not defined